apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "terraria.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "terraria.name" . }}
    helm.sh/chart: {{ include "terraria.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  terraria.json: |
{{- if .Values.terraria.settings }}
{{ toJson .Values.terraria.settings | indent 4 }}
{{- end }}
