{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "terraria.serviceAccountName" . }}
  labels:
{{ include "terraria.labels" . | indent 4 }}
{{- end -}}
