apiVersion: v1
kind: Service
metadata:
  name: {{ include "terraria.fullname" . }}
  labels:
{{ include "terraria.labels" . | indent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "terraria.fullname" . }}
{{ toYaml .Values.terraria.service.annotations | indent 4 }}
spec:
  type: {{ .Values.terraria.service.type }}
  {{ if .Values.terraria.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.terraria.service.externalTrafficPolicy }}
  {{ end }}
  {{ if .Values.terraria.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.terraria.service.loadBalancerIP }}
  {{ end }}
  ports:
    - port: {{ .Values.terraria.service.port }}
      targetPort: server
      protocol: TCP
      name: server
  selector:
    app.kubernetes.io/name: {{ include "terraria.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
